# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/PipelineCPU.srcs/VgaCPU.xdc

# IP: ip/DataRAM_1/DataRAM.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DataRAM || ORIG_REF_NAME==DataRAM} -quiet] -quiet
