# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a200tfbg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir E:/codetest/Verilogtest/lab30_Risc5CPU/vivado/Risc5CPU.cache/wt [current_project]
set_property parent.project_path E:/codetest/Verilogtest/lab30_Risc5CPU/vivado/Risc5CPU.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo e:/codetest/Verilogtest/lab30_Risc5CPU/vivado/Risc5CPU.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files E:/codetest/Verilogtest/lab30_Risc5CPU/vivado/Risc5CPU.srcs/digital.coe
read_verilog -library xil_defaultlib {
  E:/codetest/Verilogtest/lab30_Risc5CPU/src/ALU.v
  E:/codetest/Verilogtest/lab30_Risc5CPU/src/Branch.v
  E:/codetest/Verilogtest/lab30_Risc5CPU/src/Decode.v
  E:/codetest/Verilogtest/lab30_Risc5CPU/src/EX.v
  E:/codetest/Verilogtest/lab30_Risc5CPU/src/ID.v
  E:/codetest/Verilogtest/lab30_Risc5CPU/src/IF.v
  E:/codetest/Verilogtest/lab30_Risc5CPU/src/InstructionROM.v
  E:/codetest/Verilogtest/lab30_Risc5CPU/src/RBWRegisters.v
  E:/codetest/Verilogtest/lab30_Risc5CPU/src/Register.v
  E:/codetest/Verilogtest/lab30_Risc5CPU/src/Risc5CPU.v
  E:/codetest/Verilogtest/lab30_Risc5CPU/vivado/Risc5CPU.srcs/sources_1/imports/PipelineCPU.srcs/TMDSencode.v
  E:/codetest/Verilogtest/lab30_Risc5CPU/src/adder.v
  E:/codetest/Verilogtest/lab30_Risc5CPU/src/adder_32bits.v
  E:/codetest/Verilogtest/lab30_Risc5CPU/src/adder_4bits.v
  E:/codetest/Verilogtest/lab30_Risc5CPU/src/adder_4bitsx2.v
  E:/codetest/Verilogtest/lab30_Risc5CPU/vivado/Risc5CPU.srcs/sources_1/imports/PipelineCPU.srcs/button_process_unit.v
  E:/codetest/Verilogtest/lab30_Risc5CPU/src/dffre.v
  E:/codetest/Verilogtest/lab30_Risc5CPU/src/mux.v
  E:/codetest/Verilogtest/lab30_Risc5CPU/src/mux32.v
  E:/codetest/Verilogtest/lab30_Risc5CPU/vivado/Risc5CPU.srcs/sources_1/imports/PipelineCPU.srcs/syncGenarator.v
  E:/codetest/Verilogtest/lab30_Risc5CPU/vivado/Risc5CPU.srcs/sources_1/imports/PipelineCPU.srcs/vga_data.v
  E:/codetest/Verilogtest/lab30_Risc5CPU/vivado/Risc5CPU.srcs/sources_1/imports/PipelineCPU.srcs/PipelineCPUTest.v
}
read_ip -quiet E:/codetest/Verilogtest/lab30_Risc5CPU/vivado/Risc5CPU.srcs/sources_1/ip/DataRAM_1/DataRAM.xci
set_property used_in_implementation false [get_files -all e:/codetest/Verilogtest/lab30_Risc5CPU/vivado/Risc5CPU.srcs/sources_1/ip/DataRAM_1/DataRAM_ooc.xdc]

read_ip -quiet E:/codetest/Verilogtest/lab30_Risc5CPU/vivado/Risc5CPU.srcs/sources_1/ip/DCM_PLL/DCM_PLL.xci
set_property used_in_implementation false [get_files -all e:/codetest/Verilogtest/lab30_Risc5CPU/vivado/Risc5CPU.srcs/sources_1/ip/DCM_PLL/DCM_PLL_board.xdc]
set_property used_in_implementation false [get_files -all e:/codetest/Verilogtest/lab30_Risc5CPU/vivado/Risc5CPU.srcs/sources_1/ip/DCM_PLL/DCM_PLL.xdc]
set_property used_in_implementation false [get_files -all e:/codetest/Verilogtest/lab30_Risc5CPU/vivado/Risc5CPU.srcs/sources_1/ip/DCM_PLL/DCM_PLL_ooc.xdc]

read_ip -quiet E:/codetest/Verilogtest/lab30_Risc5CPU/vivado/Risc5CPU.srcs/sources_1/ip/DisplayROM/DisplayROM.xci
set_property used_in_implementation false [get_files -all e:/codetest/Verilogtest/lab30_Risc5CPU/vivado/Risc5CPU.srcs/sources_1/ip/DisplayROM/DisplayROM_ooc.xdc]

read_edif E:/codetest/Verilogtest/lab30_Risc5CPU/vivado/Risc5CPU.srcs/sources_1/imports/PipelineCPU.srcs/TMDSencode.edf
read_edif E:/codetest/Verilogtest/lab30_Risc5CPU/vivado/Risc5CPU.srcs/sources_1/imports/PipelineCPU.srcs/button_process_unit.edf
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc E:/codetest/Verilogtest/lab30_Risc5CPU/vivado/Risc5CPU.srcs/constrs_1/imports/PipelineCPU.srcs/VgaCPU.xdc
set_property used_in_implementation false [get_files E:/codetest/Verilogtest/lab30_Risc5CPU/vivado/Risc5CPU.srcs/constrs_1/imports/PipelineCPU.srcs/VgaCPU.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top PipelineCPUTest -part xc7a200tfbg484-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef PipelineCPUTest.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file PipelineCPUTest_utilization_synth.rpt -pb PipelineCPUTest_utilization_synth.pb"
